# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'git@github.com:agencyenterprise/stateful.git'

target 'StatefulExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StatefulExample
  pod 'Stateful'
end
